services:

  # On creer ici notre serveur 
  geoserver:
    image: docker.osgeo.org/geoserver:2.26.0
    environment:
      - RUN_UNPRIVILEGED=true
      - CHANGE_OWNERSHIP_ON_FOLDERS="/opt /opt/geoserver_data/ /mnt/geoserver_geodata"
      - CORS_ENABLED=true
      - SKIP_DEMO_DATA=true
      - WEBAPP_CONTEXT=cartojustice_gs
    ports:
      - "8090:8080"
    volumes:
      - ./geoserver/opt:/opt/geoserver_data
  
  web:
    image: ghcr.io/mastergeonum/cartojustice:latest
    build: .
    ports:
      - "8000:80"
      